### ISSUE TITLE
Missing Translations (seems like)

### ISSUE THREAD

**Issue by Durus-R** [Vanilla-OS/apx#205]
Hello, yesterday I installed Vanilla OS, just to get a little impression of a totally stable system :smile_cat: 
I love it!

But, there is still lots of work, also at apx.

I have configured the local to be german, but apx seems to have a problem with the translation files I think. 
An example:
![grafik](https://user-images.githubusercontent.com/68396806/231855436-db07e665-5a98-4f43-aae5-5d2be37fb023.png)

**Comment by kbdharun** [comment]
> I have configured the local to be german, but apx seems to have a problem with the translation files I think. 

The translation files were added to the repo after the latest release, as we are moving away to Debian there won't be any updates atm, you can instead install the latest version using make from repo, but I wouldn't recommend it.

**Comment by Durus-R** [comment]
Okay. Abroot has the same bug btw

**Comment by kbdharun** [comment]
> Okay. Abroot has the same bug btw

Yes, all translations for these components were done after we started working on the switch to Debian so they won't be available until the 2.0 release.

**Comment by Durus-R** [comment]
What do you mean with "switch to debian"? Are you guys about to change the package sources from ubuntu to debian???

**Comment by kbdharun** [comment]
> What do you mean with "switch to debian"? Are you guys about to change the package sources from ubuntu to debian???

Yes, we are changing our base to Debian and we are currently in the process of changing it, I would suggest you take a look at this https://vanillaos.org/2023/03/07/vanilla-os-2.0-orchid-initial-work.html.

There won't be any updates in the launchpad for apx and our other components as we have transitioned it to Debian and openSUSE's obs (Open Build Service). So that's why I suggested you wait till then next release  (we don't have an ETA for it atm).
