### ISSUE TITLE
Containers

### ISSUE THREAD

**Issue by LeandrysDEV** [Vanilla-OS/apx#209]
![Screenshot from 2023-04-18 19-35-24.png](https://user-images.githubusercontent.com/113289722/232927755-df563913-d90a-4974-aa9d-6073b6d3d6a2.png)

If you use GUI to create a container you only receive this error, every container work's equal

If you create a container from Terminal, the container doesn't not work's fine, terminal get lock and the container don't will created (at least on my pc)

**Comment by kbdharun** [comment]
You need an internet connection to create containers as it pulls the images from docker hub or the distros registry. From the image you attached above, you seem to have not set network passthrough in virt manager, if you ran the first setup it should have failed at the connection check step due to this.
